language: cpp
compiler: gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmariadbclient-dev libpoco-dev

script:
  - export CMAKE_MODULE_PATH=$CMAKE_MODULE_PATH:/usr/local
  - mkdir build && cd build
  - cmake .. && make && make test

branches:
  only:
    - master

notifications:
  recipients:
    - andyhuzhill@gmail.com
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)

